{% set name = "alibabacloud-tea" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/alibabacloud-tea-{{ version }}.tar.gz
  sha256: 2928989eaa71f455ac88750c54966f979082e97cc761ff24960129e094583b40

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests >=2.21.0,<3.0.0
    - aiohttp >=3.7.0,<4.0.0

test:
  imports:
    - Tea
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aliyun/tea-python
  summary: The tea module of alibabaCloud Python SDK.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
