{% set name = "alibabacloud-tea" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/alibabacloud-tea-{{ version }}.tar.gz
  sha256: 5b0cbe9acfab89ca1dc6b8608c5d92d0915d127bea50ac36f4d14d4200afd82a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests >=2.21.0,<3.0.0
    # handle problem with 3.9.0b0 on `main` label
    - aiohttp >=3.7.0,<=3.8.6

test:
  imports:
    - Tea
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aliyun/tea-python
  summary: The tea module of alibabaCloud Python SDK.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
